source 'https://rubygems.org'

gem 'rails', '3.2.14'

gem 'sqlite3'

gem 'openstax_connect', :path => '..'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'quiet_assets'
gem 'debugger'

gem 'openstax_utilities', '~> 0.0.7'
gem 'lev', '>= 0.0.2'

gem 'thin'
